import '../styles/globals.css';
import 'react-datepicker/dist/react-datepicker.css';
import type { AppProps, NextWebVitalsMetric } from 'next/app';

import { withTRPC } from '@trpc/next';
import { AppRouter } from './api/trpc/[trpc]';

import { Provider } from 'react-redux';
import Head from 'next/head';

import { store } from '../store';

import Header from '../components/header';
import AppLayout from '../components/appLayout';

function MyApp({ Component, pageProps }: AppProps) {
  const AnyComponent = Component as any;
  return (
    <Provider store={store}>
      <Head>
        <title>VSELF APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <>
          <Header />
          <div className="grid place-items-center h-screen">
            <AnyComponent {...pageProps} />
          </div>
        </>
      </AppLayout>
    </Provider>
  );
}

export function reportWebVitals(metric: NextWebVitalsMetric) {
  console.log('metric: ', metric);
}

export default withTRPC<AppRouter>({
  config({ ctx }) {
    /**
     * If you want to use SSR, you need to use the server's full URL
     * @link https://trpc.io/docs/ssr
     */
    const url = process.env.VERCEL_URL
      ? `https://${process.env.VERCEL_URL}/api/trpc`
      : 'http://localhost:3000/api/trpc';

    return {
      url,
      /**
       * @link https://react-query.tanstack.com/reference/QueryClient
       */
      // queryClientConfig: { defaultOptions: { queries: { staleTime: 60 } } },
    };
  },
  /**
   * @link https://trpc.io/docs/ssr
   */
  ssr: true,
})(MyApp);
