import '../styles/globals.css';
import 'react-datepicker/dist/react-datepicker.css';
import styles from '../styles/Home.module.css';
import type { AppProps, NextWebVitalsMetric } from 'next/app';
import { Provider } from 'react-redux';
import Head from 'next/head';

import { store } from '../store';

import Header from '../components/header';
import AppLayout from '../components/appLayout';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Provider store={store}>
      <Head>
        <title>VSELF APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <>
          <Header />
          <div className="grid place-items-center h-screen">
            <div className={`${styles.container} relative`}>
              <Component {...pageProps} />
            </div>
          </div>
        </>
      </AppLayout>
    </Provider>
  );
}

export function reportWebVitals(metric: NextWebVitalsMetric) {
  console.log('metric: ', metric);
}

export default MyApp;
